aodn wave site names - only 1st letter upcase
aodn/harvesters pull request #1017
Opened 2023-05-30 06:59 UTC by ana-berger

2023-05-30 07:00 UTC, ana-berger commented
this was totally a chatGPT 'doing'!

2023-05-31 01:08 UTC, bpasquer requested changes

2023-05-31 01:08 UTC, bpasquer commented on workspace/AODN_WAVE/process/DataHarvest/HarvestFile_WaveGeneric_RT_0.1.item
> +        <mapperTableEntries name="sitename" expression="row1.site_name.toLowerCase().substring(0, 1).toUpperCase() + row1.site_name.toLowerCase().substring(1) " type="id_String"/>
there's no need to convert to lowercase first. It's done in the second part of the line

2023-05-31 01:10 UTC, ana-berger commented on workspace/AODN_WAVE/process/DataHarvest/HarvestFile_WaveGeneric_RT_0.1.item
> +        <mapperTableEntries name="sitename" expression="row1.site_name.toLowerCase().substring(0, 1).toUpperCase() + row1.site_name.toLowerCase().substring(1) " type="id_String"/>
hum ok, I will test, but that's what chatGPT told me to do

2023-05-31 04:41 UTC, ana-berger commented on workspace/AODN_WAVE/process/DataHarvest/HarvestFile_WaveGeneric_RT_0.1.item
> +        <mapperTableEntries name="sitename" expression="row1.site_name.toLowerCase().substring(0, 1).toUpperCase() + row1.site_name.toLowerCase().substring(1) " type="id_String"/>
> there's no need to convert to lowercase first. It's done in the second part of the line

done!

2023-05-31 04:46 UTC, bpasquer approved these changes

2023-05-31 04:46 UTC, merged